# version: 0.0
# os: linux
# files:
#   - source: /
#     destination: /home/ec2-user/express-app
# hooks:
#   ApplicationStop:
#     - location: scripts/application_stop.sh
#       timeout: 300
#       runas: ec2-user
#   BeforeInstall:
#     - location: scripts/before_install.sh
#       timeout: 300
#       runas: ec2-user
#   ApplicationStart:
#     - location: scripts/application_start.sh
#       timeout: 300
#       runas: ec2-user
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/github_actions_testrepo
    overwrite: yes

#BeforeInstall, AfterInstall(codeDeploy 수명주기)에 실행될 파일 지정
# hooks:
#   BeforeInstall:
#     - location: scripts/before_deploy.sh
#       runas: ubuntu
#   AfterInstall:
#     - location: scripts/after-deploy.sh
#       timeout: 180
#       runas: ubuntu